import type { Metadata } from 'next'
// import localFont from "next/font/local";
import '@theme/stylesheets/reset.min.css'
import '@theme/stylesheets/main.scss'
import '@theme/stylesheets/layers.scss'
import '@theme/stylesheets/palette.scss'
import '@theme/stylesheets/spacing.scss'
import '@theme/stylesheets/pageMargin.scss'
import '@theme/stylesheets/typography.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={``}>{children}</body>
    </html>
  )
}
